### ISSUE TITLE
Pull movies and their information from firebase.

### ISSUE THREAD

**Issue by H4RT4N** [SBoulanger/NotFlix#95]
I've checked the History profile and some tutorials online but I'm having issues accessing the Firestore. I think I need more references if anyone has been assessing and pulling stuff from the database in their code.

**Comment by kaywalton** [comment]
I think this is being blocked by the changes made to the Firestore.js file. When we use a basic app.init(config) like we did before, everything goes back to working.

**Comment by H4RT4N** [comment]
Its been resolved thanks to the API Timothy provided.
